#!/usr/bin/env bash

[ -f /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion

# Git
for file in /usr/share/git/completion/*.{bash,sh}; do
  [ -f "$file" ] && . "$file"
done

if type _git &>/dev/null; then
  complete -o default -o nospace -F _git g
fi
